OPENFHE_TAG=v1.2.3
OPENFHE_PYTHON_TAG=v0.8.10
# WHEEL_VERSION is OPENFHE_PYTHON_TAG's version (numners only)
WHEEL_VERSION=0.8.10
PYTHON_VERSION=3.12
# c++
CXX_COMPILER=g++-14
C_COMPILER=gcc-14
PARALELLISM=11
